### ISSUE TITLE
How to get the floats of another user's inventory?

### ISSUE THREAD

**Issue by Zendrex** [DoctorMcKay/node-globaloffensive#12]
So right now im using steamcommunity to get another user's inventory. From there im using a map of the array to get the inspect link as shown below,

```
inventory.map(function(item)
    var inspectURL = JSON.stringify(item['actions'][0]['link'])
    var d = inspectURL.split("D").pop().slice(0, -1);
    var assetID = item['assetid'];
    var itemID = item['id'];
    var apiURL = ('steam://rungame/730/76561202255233023/+csgo_econ_action_preview%20S' + steamID64 + 'A' + assetID + 'D' + d)
})
```

However im stumped when it comes to having it loop through the array. I get maybe 2 at most with a` for item in inventory` loop but that the best i get... Any help would be appreciated.

**Comment by DoctorMcKay** [comment]
You can't, really. You can only query one item at a time and it's limited to ~1 item per second so for a 60-item inventory (which is small) it would take a minute. It only goes up from there.
