### ISSUE TITLE
No GC response

### ISSUE THREAD

**Issue by kiwec** [DoctorMcKay/node-globaloffensive#18]
CSGO was launched on the account ; it is level 2 in-game.

```
Logging in to Steam...
Logged in to Steam as [some SteamID]
Connecting because we're playing CS:GO
Sending GC message ClientHello
Sending hello, setting timer for next attempt to 2000 ms
Sending GC message ClientHello
Sending hello, setting timer for next attempt to 4000 ms
# etc.
```

Here's the entire source code : 
https://gist.github.com/kiwec/48dc3a12bd1b31064ad7037ca982cc37

Any ideas as to why it doesn't work ?

**Comment by DoctorMcKay** [comment]
Does your account own CS:GO?

**Comment by kiwec** [comment]
> CSGO was launched on the account

**Comment by DoctorMcKay** [comment]
Maybe the GC was down at the time.

**Comment by kiwec** [comment]
Nope, it wasn't. I launched the game to test it.

**Comment by fantik11** [comment]
Have this problem too

**Comment by chavychaze** [comment]
It looks like some problem with CS GO id(730) connection, cuz when I change to Team Fortness id(440), it connects fine. Any ideas

**Comment by DoctorMcKay** [comment]
Does your account own CS:GO?

**Comment by chavychaze** [comment]
yes, for sure, but I definitely don't have team fortness

**Comment by DoctorMcKay** [comment]
TF2 is in Steam sub 0, so all Steam accounts own it without having to request a license for it.

When your bot "launches" CS:GO, does it display that on its profile?

**Comment by chavychaze** [comment]
and I also use steam key to login(mb it gives a clue)

**Comment by chavychaze** [comment]
> TF2 is in Steam sub 0, so all Steam accounts own it without having to request a license for it.
> 
> When your bot "launches" CS:GO, does it display that on its profile?

CS GO also free to play now, or I should buy some premium account to have access.
When I console.log csgo, or client variable, it gives some information from my steam account, so I think yes.
It starts reconnecting  when send a steam game key(730), and error occurs on this step

**Comment by DoctorMcKay** [comment]
CS:GO is free to play, yes, but it's not in Steam sub 0. You need to [request a free-on-demand license](https://github.com/DoctorMcKay/node-steam-user#requestfreelicenseappids-callback) (once) to actually own it.

**Comment by chavychaze** [comment]
thank you, I'll try it tomorrow, and thanks to answering me in such short period of time, thank you))

**Comment by chavychaze** [comment]
Still, don't work, `requestFreeLicense` on callback returns that `err === null`, but other two variables are empty arrays. Also, ask my friends steam key (he bought CS GO) and the result is the same. 
Maybe some problem with my code
https://gist.github.com/chavychaze/b16994afc4a4549f903a830a8f3e933a

**Comment by DoctorMcKay** [comment]
You still need to specify your accountName even if you're logging in with a loginKey.

**Comment by chavychaze** [comment]
I updated the [file](https://gist.github.com/chavychaze/b16994afc4a4549f903a830a8f3e933a) to a working version.
Thank you very much everything works fine.
I think you can close this issue, cuz except me, this guys probably gives up))
