### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by tabam1** [DoctorMcKay/node-globaloffensive#19]
this.emit('disconnectedFromGC', TeamFortress2.GCGoodbyeReason.NO_SESSION); <- ReferenceError: TeamFortress2 is not defined 
globaloffensive/index.js:75:36

**Comment by DoctorMcKay** [comment]
Thanks, fixed in [v2.0.1](https://github.com/DoctorMcKay/node-globaloffensive/releases/tag/v2.0.1).
