### ISSUE TITLE
ReferenceError crash in index.js

### ISSUE THREAD

**Issue by frk1** [DoctorMcKay/node-globaloffensive#2]
https://github.com/DoctorMcKay/node-globaloffensive/blob/4ffece8e63f8b5d4a62a1b1efb870ca9929e5ad1/index.js#L28

This line will crash if reached, since type is not defined in this context.

![screen shot 2016-07-07 at 14 35 56](https://cloud.githubusercontent.com/assets/11559382/16653276/2702fdca-4450-11e6-8609-688a10fa1785.png)

**Comment by DoctorMcKay** [comment]
Whoops! Fixed in v1.1.2.
