### ISSUE TITLE
New function

### ISSUE THREAD

**Issue by tabam1** [DoctorMcKay/node-globaloffensive#20]
You can add: sendCommend

this._send(Language.ClientCommendPlayer, Protos.CMsgGCCStrike15_v2_ClientCommendPlayer, {
		accountId: steamid.accountid,
		matchId: 8,
		tokens: 10,
		commendation: {
            cmdFriendly: 1,
            cmdTeaching: 2,
            cmdLeader: 4
        }
	});

AND sendReport

this._send(Language.ClientReportPlayer, Protos.CMsgGCCStrike15_v2_ClientReportPlayer, {
		accountId: steamid.accountid,
        matchId: matchID ? matchID : 8,
        rptAimbot: 2,
        rptWallhack: 3,
        rptSpeedhack: 4,
        rptTeamharm: 5,
        rptTextabuse: 6,
        rptVoiceabuse: 7
	});

**Comment by DoctorMcKay** [comment]
No.
