### ISSUE TITLE
[Question] Entering Steam Code before fetching data

### ISSUE THREAD

**Issue by helloitsm3** [DoctorMcKay/node-globaloffensive#27]
I'm currently using Express to run the node-globaloffensive module for my app. Every time I sign in, it'll ask me for my steam code and once I entered it, it'll take a long time to load and my web app will timeout. How do I efficiently enter steam code without causing my web app to crash?

```javascript
user.on("loggedOn", function(details) {
  console.log("Logged into Steam as " + user.steamID.getSteam3RenderedID());
  user.setPersona(SteamUser.EPersonaState.Online);
  user.gamesPlayed([730]);
  console.log("Done setting Games Played");
});

user.on("steamGuard", function(domain, callback) {
  console.log("Steam Guard code needed from email ending in " + domain);
  router.post("/", function(req, res) {
    console.log(`SteamGuard: ${req.body.steam_guard}`);
    callback(req.body.steam_guard);
  });
});
```

**Comment by DoctorMcKay** [comment]
You're better off keeping an account signed in 24/7 and just direct requests to it as they come in.
