### ISSUE TITLE
How to parse prime status

### ISSUE THREAD

**Issue by fantik11** [DoctorMcKay/node-globaloffensive#32]
Hello, I need to parse prime status of account, how i can do it with this library? I am nothing found in readme, so i decided to ask it

**Comment by DoctorMcKay** [comment]
No, this isn't currently possible.

**Comment by DoctorMcKay** [comment]
My current suspicion is that the GC doesn't actually send back to the client whether it's prime or not. I think the client checks with Steam to see if it has a phone number, and then also checks whether it owns app 624820 (the paid method) or if it's rank 21 (the free method).

You should be able to do all this with node-steam-user and node-globaloffensive already, so there's no point in adding a separate function to do this.
