### ISSUE TITLE
inspectItem only works for some steam accounts 

### ISSUE THREAD

**Issue by jcohenho** [DoctorMcKay/node-globaloffensive#33]
Hi there,

Is there any reason that `csgo.inspectItem` method would only work for some steam accounts but not for others? I can successfully get item data returned from one steam account, but not when I try it from another. Are there settings that need to be configured that I may be forgetting about?

**Comment by jcohenho** [comment]
Found the problem! The other steam account did not have CS:GO added to its library. The game needs to be added, and perhaps booted up and then inspect inventory in-game first.

**Comment by DoctorMcKay** [comment]
You can use [`requestFreeLicense`](https://github.com/DoctorMcKay/node-steam-user#requestfreelicenseappids-callback) to request a license for a free game.
