### ISSUE TITLE
How to check the float?

### ISSUE THREAD

**Issue by ProNikolay37** [DoctorMcKay/node-globaloffensive#34]
I created js file in which I registered this:

const SteamUser = require('steam-user');
const GlobalOffensive = require('globaloffensive');

let user = new SteamUser();
let csgo = new GlobalOffensive(user);

user.logOn({
	"accountName": "...",
	"password": "..."
});
user.on('loggedOn', function(details) {
	console.log("Logged into Steam as " + user.steamID.getSteam3RenderedID());
	user.setPersona(SteamUser.EPersonaState.Online);
	user.gamesPlayed(730);
csgo.inspectItem('steam://rungame/730/76561202255233023/+csgo_econ_action_preview%20S76561198334769752A16578240883D14421726855138953619')
  user.logOff();
});

Why can't I get float?

**Comment by DoctorMcKay** [comment]
Because you didn't wait for a GC session.
