### ISSUE TITLE
server_id

### ISSUE THREAD

**Issue by toorisrael** [DoctorMcKay/node-globaloffensive#39]
What exactly is server_id in matchList (requestLiveGameForUser)? Should it be server's steamid? If so, it has wrong value or it's some kind of conversion problem:

> FULLY CONNECTED!!
> [
>   {
>     roundstatsall: [],
>     matchid: '3386139258250068207',
>     matchtime: null,
>     watchablematchinfo: {
>       server_ip: null,
>       tv_port: null,
>       tv_spectators: 0,
>       tv_time: 1998,
>       tv_watch_password: null,
>       cl_decryptdata_key: null,
>       cl_decryptdata_key_pub: null,
>       game_type: 32776,
>       game_mapgroup: 'mg_de_mirage',
>       game_map: 'de_mirage',
>       server_id: '9295711545907311873',
>       match_id: '3386139258250068207',
>       reservation_id: null
>     },
>     roundstats_legacy: {
>       kills: [Array],
>       assists: [Array],
>       deaths: [Array],
>       scores: [Array],
>       pings: [],
>       team_scores: [Array],
>       enemy_kills: [],
>       enemy_headshots: [],
>       enemy_3ks: [],
>       enemy_4ks: [],
>       enemy_5ks: [],
>       mvps: [Array],
>       enemy_kills_agg: [],
>       reservationid: null,
>       reservation: [Object],
>       map: null,
>       round: null,
>       round_result: null,
>       match_result: null,
>       confirm: null,
>       reservation_stage: null,
>       match_duration: 1909,
>       spectators_count: null,
>       spectators_count_tv: null,
>       spectators_count_lnk: null,
>       drop_info: null
>     }
>   }
> ]

example server's SteamID:

> [A:1:1117543424:13807]
> 90131294278409216

I'm just a begginer, I will be grateful if you could explain it to me.
Thanks!

**Comment by DoctorMcKay** [comment]
Sorry, I don't know.
