### ISSUE TITLE
Is it possible to get the Wingman and/or Danger Zone rank?

### ISSUE THREAD

**Issue by Wurstfach404** [DoctorMcKay/node-globaloffensive#44]
If yes = how?

**Comment by DoctorMcKay** [comment]
It will be possible in the next release.

**Comment by Bl4CkGuuN** [comment]
Are there any news about the next release?

**Comment by DoctorMcKay** [comment]
2.1.0 was the next release after that comment. Can it not do what you're looking for? If not, I don't really remember the context of this request.

**Comment by Bl4CkGuuN** [comment]
I'm actually still using the 2.0.4 :D
The question was just if it is possible to get the Wingman and/or Danger Zone rank. Can't find anything related in the changelog :)
