### ISSUE TITLE
 is it possible to use storage unit?

### ISSUE THREAD

**Issue by Kolosok86** [DoctorMcKay/node-globaloffensive#46]
anyone can help with this, I will be very grateful!

**Comment by DoctorMcKay** [comment]
Not at the moment.

**Comment by Kolosok86** [comment]
I solved the problem, if it’s not difficult for you, you can add methods, spent more than two days on it. Tnx @DoctorMcKay

`GlobalOffensive.prototype.getCasket = function(casket) {
	this._send(Language.CasketItemLoadContents, Protos.CMsgCasketItem, { "casket_item_id": casket, "item_item_id": casket })
};

GlobalOffensive.prototype.addToCasket = function(casket, asset_id) {
	this._send(Language.CasketItemAdd, Protos.CMsgCasketItem, { "casket_item_id": casket, "item_item_id": asset_id })
};

GlobalOffensive.prototype.removeFromCasket = function(casket, asset_id) {
	this._send(Language.CasketItemExtract, Protos.CMsgCasketItem, { "casket_item_id": casket, "item_item_id": asset_id })
};`

**Comment by Kolosok86** [comment]
the response from the server comes in the form of emit (add in index.js if need)
```
csgoClient.on('itemAcquired', (item) => {
    console.log(item);
})
```

**Comment by DoctorMcKay** [comment]
Added in [v2.1.0](https://github.com/DoctorMcKay/node-globaloffensive/releases/tag/v2.1.0).
