### ISSUE TITLE
npm install globaloffensive  npm ERR!

### ISSUE THREAD

**Issue by mrranger** [DoctorMcKay/node-globaloffensive#47]
npm install globaloffensive
npm ERR! code ENOSELF
npm ERR! Refusing to install package with name "globaloffensive" under a package
npm ERR! also called "globaloffensive". Did you name your project the same
npm ERR! as the dependency you're installing?
npm ERR!
npm ERR! For more information, see:
npm ERR!     <https://docs.npmjs.com/cli/install#limitations-of-npms-install-algorithm>

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\RANGERSTUDIO\AppData\Roaming\npm-cache\_logs\2020-02-09T08_33_32_267Z-debug.log

**Comment by Exokay** [comment]
Did you read your error message?
npm ERR! Refusing to install package with name "globaloffensive" under a package
npm ERR! also called "globaloffensive". Did you name your project the same
