### ISSUE TITLE
Get item's name in inventory

### ISSUE THREAD

**Issue by Flodkozza** [DoctorMcKay/node-globaloffensive#48]
The items don't have any attribute for name or anything that indicates which item it is. Is it possible to get that somehow?

**Comment by k1de** [comment]
You can use **node-steam-tradeoffer-manager**
[https://github.com/DoctorMcKay/node-steam-tradeoffer-manager/wiki/TradeOfferManager#getinventorycontentsappid-contextid-tradableonly-callback](url)
or
[https://github.com/DoctorMcKay/node-steam-tradeoffer-manager/wiki/TradeOfferManager#getuserinventorycontentssteamid-appid-contextid-tradableonly-callback](url)
callback will be like that
[https://github.com/DoctorMcKay/node-steam-tradeoffer-manager/wiki/EconItem](url)

**Comment by DoctorMcKay** [comment]
The way the CS:GO inventory system works, it actually is best to just use node-steamcommunity or node-steam-tradeoffer-manager to get an item's basic details. Using node-globaloffensive is really meant for getting the data you can't get from the Steam Community APIs.
