### ISSUE TITLE
get item names from storage unit?

### ISSUE THREAD

**Issue by nightmare6767** [DoctorMcKay/node-globaloffensive#49]
hello,
i use node steamcommunity to fetch inventory but is there a way i can get items in storage units with their names?

would appreciate any help

**Comment by DoctorMcKay** [comment]
No, it's not possible to retrieve any data about what's in a storage unit without connecting to the GC using the account that owns the storage unit.

**Comment by nightmare6767** [comment]
i meant for myself i will connect to GC but i did not see a way to get item names only ids

**Comment by DoctorMcKay** [comment]
It's technically possible to figure out what particular items are from the GC data, but CS:GO is a complete mess and you're far better off keeping track of what items map to what IDs before you put them into your storage unit.
