### ISSUE TITLE
inspect item screenshot and 3d model(with texture)

### ISSUE THREAD

**Issue by lid-ut** [DoctorMcKay/node-globaloffensive#51]
Hi, I’m developing a skin exchange service, and would like to know if it is possible to request a screenshot in the inspectItem? 
I am ready to pay for it.

**Comment by lid-ut** [comment]
EMsgGCItemPreviewRequest is this exactly what I need? If so, how to work with it?

**Comment by DoctorMcKay** [comment]
No, it's not possible.
