### ISSUE TITLE
How can I get the LiveGame?

### ISSUE THREAD

**Issue by Wurstfach404** [DoctorMcKay/node-globaloffensive#56]
I want to get the live game of a specific steam user.
With `csgo.requestLiveGameForUser(account_id)` I get:
```
Sending GC message MatchListRequestLiveGameForUser
Got unhandled GC message 9173
Got handled GC message MatchmakingGC2ClientHello
Got unhandled GC message 9194
Got unhandled GC message 9173
Got handled GC message MatchList
```

But how can I see the data, that I received from the GC?

**Comment by Wurstfach404** [comment]
Okay, I got it with:
```
csgo.on('matchList', async (data) => {
    console.log(data);
});
```

Can I somehow get all connected player with this information?

**Comment by Bl4CkGuuN** [comment]
That should work: `console.log( data[0].roundstats_legacy.reservation.account_ids);`

**Comment by Wurstfach404** [comment]
Oh yeah, that works. Thank you :)
