### ISSUE TITLE
requestLiveGameForUser

### ISSUE THREAD

**Issue by patrykczubek** [DoctorMcKay/node-globaloffensive#59]
Hi, while requesting game info while in a competetive game by doing 
```
csgo.requestLiveGameForUser('76561198400109811')
```
and listening on
```
csgo.on('matchList', (data) => {
    console.log(data)
})
```
I don't get any data in the listener. Am I requesting it wrong or did something break recently?

**Comment by DoctorMcKay** [comment]
I've read reports that Valve disabled that request.
