### ISSUE TITLE
Get image by sticker id 

### ISSUE THREAD

**Issue by fortza** [DoctorMcKay/node-globaloffensive#7]
do you have any idea how to get sticker image with sticker id ?

**Comment by Exokay** [comment]
u normally get the sticker image link via the inventory json item data.  ex.
`{"type":"html","value":"<br><div id=\"sticker_info\" name=\"sticker_info\" title=\"Sticker Details\" style=\"border: 2px solid rgb(102, 102, 102); border-radius: 6px; width=100; margin:4px; padding:8px;\"><center><img width=64 height=48 src=\"https://steamcdn-a.akamaihd.net/apps/730/icons/econ/stickers/community02/mylittlefriend.6515b596e3560fb620f5b9524a504981fd7c0c2d.png\"><br>Sticker: My Little Friend</center></div>"}],`  
thats not helping getting it via the sticker id but its a start.
