### ISSUE TITLE
vac_banned always null

### ISSUE THREAD

**Issue by ItzArty** [DoctorMcKay/node-globaloffensive#72]
It seems weird, but I have an account which has a vac ban issued on it and for some reason `requestPlayersProfile()` issued on my own ID everytime returns `vac_banned: null`, anyone knows what is up with that behavior?

**Comment by DoctorMcKay** [comment]
The structure of the data returned (the keys, like `vac_banned`) is defined by Valve, but that doesn't necessarily mean that they *send* all that data.
