### ISSUE TITLE
How can I loop an inventory with "inspectItem(owner[, assetid][, d][, callback])"

### ISSUE THREAD

**Issue by eric101110** [DoctorMcKay/node-globaloffensive#8]
I only get one item if I loop inventory of items , is there something I'm missing? Should I queue this method?

**Comment by DoctorMcKay** [comment]
All the data available from `inspectItem` is already present in the `inventory` array, namely in the attributes.

**Comment by eric101110** [comment]
Nice , thanks!

**Comment by eric101110** [comment]
The attribute I'm looking for is float , Is it in the ByteBuffer?
![31a92ebeed94aa6b393fb58441d8542e](https://cloud.githubusercontent.com/assets/13051215/24840966/c7a59416-1d78-11e7-8147-cf125daf025e.png)

**Comment by DoctorMcKay** [comment]
Wear?

**Comment by eric101110** [comment]
Yes

**Comment by DoctorMcKay** [comment]
Find the attribute with defIndex 8, and then call `valueBytes.readFloat()`.

**Comment by eric101110** [comment]
Works perfectly , Thanks for your work.

**Comment by middoors** [comment]
> All the data available from `inspectItem` is already present in the `inventory` array, namely in the attributes.

but I should be logged in with the owner of the inventory in order to see 'inventory' array right?
I want to also loop through all items of someone else's inventory which I believe is only possible via 'inspectItem()' method. Please correct me if I have got that wrong.

**Comment by DoctorMcKay** [comment]
Yes, you need to be logged into the account to get its item data via the inventory.

You *can* loop over someone else's items and inspect them one by one, but expect it to take a long time. You can only inspect one item every 1-2 seconds.

**Comment by middoors** [comment]
is there any alternative/library where I would be able to loop over someone else's items faster? There should be because many skin trading websites are already doing that.

**Comment by DoctorMcKay** [comment]
No, this is the only way.

**Comment by gustavo-dev** [comment]
@DoctorMcKay regarding what @middoors said, would you say it is possible to get banned when using lots of bots in a webserver to inspect multiple items at the same time?

**Comment by DoctorMcKay** [comment]
Anything is possible. If you're going to make a lot of requests, I'd do it with a lot of accounts.
