### ISSUE TITLE
game_map is empty

### ISSUE THREAD

**Issue by a361570441** [DoctorMcKay/node-globaloffensive#82]
hello, i wonder why game_map 's data is empty when i request data with a sharecode? Actually only cl_decryptdata_key_pub has data
"watchablematchinfo":{
                "server_ip":0,
                "tv_port":0,
                "tv_spectators":0,
                "tv_time":null,
                "tv_watch_password":null,
                "cl_decryptdata_key":null,
                "cl_decryptdata_key_pub":"10248268063719735511",
                "game_type":null,
                "game_mapgroup":null,
                "game_map":null,
                "server_id":null,
                "match_id":null,
                "reservation_id":null
            },
            "roundstats_legacy":null
        }

**Comment by brenodouglas** [comment]
In my case, don't have data in `watchablematchinfo`
```json
{
  match: [
    {
      roundstatsall: [Array],
      matchid: '3670300737004372028',
      matchtime: 1709116966,
      watchablematchinfo: [Object],
      roundstats_legacy: null
    }
  ],
  roundstatsall: undefined,
  watchablematchinfo: undefined
}
```

**Comment by DoctorMcKay** [comment]
That's just what the backend sends. I don't have any control over Valve's GC backend.
