### ISSUE TITLE
custom_name is empty on 3.0.0

### ISSUE THREAD

**Issue by nombersDev** [DoctorMcKay/node-globaloffensive#83]
In version 3.0.0 the custom_name attribute will always be null for me. Here's an example of an inventory object in version 2.3.1: 

`{
    "attribute": [
      {
        "def_index": 111,
        "value": null,
        "value_bytes": { "type": "Buffer", "data": [10, 4, 84, 101, 115, 116] }
      },
      {
        "def_index": 270,
        "value": null,
        "value_bytes": { "type": "Buffer", "data": [0, 0, 0, 0] }
      },
      {
        "def_index": 271,
        "value": null,
        "value_bytes": { "type": "Buffer", "data": [210, 115, 47, 101] }
      }
    ],
    "equipped_state": [],
    "id": "19705831414",
    "account_id": 1115033764,
    "inventory": 3,
    "def_index": 1201,
    "quantity": 1,
    "level": 1,
    "quality": 4,
    "flags": 0,
    "origin": 2,
    "custom_name": "Test",
    "custom_desc": null,
    "interior_item": null,
    "in_use": false,
    "style": null,
    "original_id": null,
    "rarity": 1,
    "position": 3,
    "casket_contained_item_count": 0
  }`

And here it is in version 3.0.0: 

`{
    "attribute": [
      { "def_index": 111, "value": null, "value_bytes": { "type": "Buffer", "data": [10, 4, 84, 101, 115, 116] } },
      { "def_index": 270, "value": null, "value_bytes": { "type": "Buffer", "data": [0, 0, 0, 0] } },
      { "def_index": 271, "value": null, "value_bytes": { "type": "Buffer", "data": [210, 115, 47, 101] } }
    ],
    "equipped_state": [],
    "id": "19705831414",
    "account_id": 1115033764,
    "inventory": 3,
    "def_index": 1201,
    "quantity": 1,
    "level": 1,
    "quality": 4,
    "flags": 0,
    "origin": 2,
    "custom_name": null,
    "custom_desc": null,
    "interior_item": null,
    "in_use": false,
    "style": null,
    "original_id": null,
    "rarity": 1,
    "position": 3
  }`

Running on node `20.4.0` // Steam user at `4.29.0`

**Comment by DoctorMcKay** [comment]
I cannot reproduce this. `custom_name` is working fine for me on 3.0.0.
