### ISSUE TITLE
Can't load full inventory of floats

### ISSUE THREAD

**Issue by Infrox** [DoctorMcKay/node-globaloffensive#9]
Hello,
I've been having a weird problem. I tried looping through the user inventory (not my own) and getting the floats but it only returns one item.
Also I tried to queue the requests like this:
`Init.prototype.getDetails = function(inventory,index,callback)
{
	var _self = this;
	for(var i = index; i < inventory.length; i++)
	{
		if(inventory[i].inspect === "none") continue;
		else
		{
			var index = i;
	_self.instances.globalOffensive.inspectItem(inventory[index].inspect,undefined,undefined,function(item){
				console.log(item);
				_self.getDetails(inventory,index+1,callback);
			});
			break;
		}

	}
}`

But that loads 3 items and stops. The callback is not getting called anymore. How do I correctly fetch all floats,paint seeds etc from an inventory?

**Comment by DoctorMcKay** [comment]
It's severely rate-limited. You need to slow down.

This means that it's highly impractical to retrieve such data for a user's entire inventory.
