### ISSUE TITLE
Game server trade offers

### ISSUE THREAD

**Issue by aligatorr89** [DoctorMcKay/node-globaloffensive#91]
Hi again @DoctorMcKay !

As you know, Valve made Steam API Key redundant, and you need to get access token from user, which is shaddy and unfeasible.

**Do you know if we can obtain trade offers from CS2 game server?** We can still access singular GetTradeOffer endpoint, and seems like CS2Float is using this now. Or anything usefull that would help us?

I can only show appreciation by rewarding you for a guide, so that's what I will do :)

**Comment by DoctorMcKay** [comment]
No, why would you think this would be possible? Game servers obviously can't trade.

**Comment by aligatorr89** [comment]
What about other ways without using session hijack or accessToken ? Access token is a bit weird to describe users they need to copy paste it from console. Also, there is a chance Steam notice weird activity with it and ban account?

**Comment by DoctorMcKay** [comment]
I'm not here to engineer your systems for you. What's available is what's available.
