### ISSUE TITLE
Ghost items in inventory

### ISSUE THREAD

**Issue by NikittyS** [DoctorMcKay/node-globaloffensive#96]
Hi. I have fresh account with cs2 prime, there is 4 items in inventory - two empty storage units, one skin and one crate. 
If I get a list of items through this module, there are more items than I see in the game inventory. Besides my items, there are four more.

This two items with strange IDs
`[{"attribute":[],"equipped_state":[],"id":"17293822569102708641","account_id":1730000000,"inventory":3221225477,"def_index":4001,"quantity":1,"level":1,"quality":4,"flags":24,"origin":8,"custom_name":null,"custom_desc":null,"interior_item":null,"in_use":false,"style":null,"original_id":null,"rarity":1,"position":0},{"attribute":[{"def_index":6,"value":null,"value_bytes":{"type":"Buffer","data":[0,0,250,66]}}],"equipped_state":[],"id":"17293822569110896676","account_id":1730000000,"inventory":3221225477,"def_index":36,"quantity":1,"level":1,"quality":1,"flags":24,"origin":8,"custom_name":null,"custom_desc":null,"interior_item":null,"in_use":false,"style":null,"original_id":null,"rarity":4,"position":0,"paint_index":125}]`

And these two look like graffiti
`[{"attribute":[{"def_index":277,"value":null,"value_bytes":{"type":"Buffer","data":[1,0,0,0]}},{"def_index":113,"value":null,"value_bytes":{"type":"Buffer","data":[197,6,0,0]}},{"def_index":233,"value":null,"value_bytes":{"type":"Buffer","data":[19,0,0,0]}}],"equipped_state":[],"id":"37944853743","account_id":1730000000,"inventory":1,"def_index":1348,"quantity":1,"level":1,"quality":4,"flags":0,"origin":24,"custom_name":null,"custom_desc":null,"interior_item":null,"in_use":false,"style":null,"original_id":null,"rarity":1,"position":1,"stickers":[{"slot":0,"sticker_id":1733,"wear":null,"scale":null,"rotation":null,"offset_x":null,"offset_y":null}]},{"attribute":[{"def_index":277,"value":null,"value_bytes":{"type":"Buffer","data":[1,0,0,0]}},{"def_index":113,"value":null,"value_bytes":{"type":"Buffer","data":[185,6,0,0]}},{"def_index":233,"value":null,"value_bytes":{"type":"Buffer","data":[14,0,0,0]}}],"equipped_state":[],"id":"37944853744","account_id":1730000000,"inventory":1,"def_index":1348,"quantity":1,"level":1,"quality":4,"flags":0,"origin":24,"custom_name":null,"custom_desc":null,"interior_item":null,"in_use":false,"style":null,"original_id":null,"rarity":1,"position":1,"stickers":[{"slot":0,"sticker_id":1721,"wear":null,"scale":null,"rotation":null,"offset_x":null,"offset_y":null}]}]`

But I don't have any graffiti, and I haven't had any in the past. May be you can explain what is that?

**Comment by DoctorMcKay** [comment]
I don't know a ton about CS2, but in TF2 things like contracts (I believe the CS equivalent is operations?) are communicated to the client as CSOEconItem objects with a specific flag (NotEcon) set to indicate that they aren't actually econ items. What you're seeing is likely something like that.

Both of your mystery items have a flags value of 24. That includes 8 (24 = 8 + 16), which is NotEcon.

**Comment by NikittyS** [comment]
Thanks for your answer about the first two items. I figured out what about the second two. It's a weekly reward where the game offers to choose 2 items out of 4. Items that aren't chosen have an attribute with definex 277 and are simply hidden from the inventory. Maybe this information will help someone.

"277"
{
  "name"      "free reward status"
  "attribute_class"       "free_reward_status"
  "description_format"        "value_is_additive"
  "hidden"        "1"
  "effect_type"       "neutral"
  "stored_as_integer"     "1"
}

**Comment by YangGuofu** [comment]
> Thanks for your answer about the first two items. I figured out what about the second two (graffiti). It's a weekly reward where the game offers to choose 2 items out of 4. Items that aren't chosen have an attribute with definex 277 and are simply hidden from the inventory. Maybe this information will help someone.
> 5free_reward_status" "description_format" "value_is_additive" "hidden" "1" "effect_type" "neutral" "stored_as_integer" "1" }

Hi. I’m now attempting to to redeem weekly rewards and I found the proto "CMsgGCCstrike15_v2_ClientRedeemFreeReward" but I don't know how to get the parameter "generation_time". Could you provide some guidance on this? Thank you so much.
